<?php

/**
 * @file
 * Contains custom_company.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_company_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_company module.
    case 'help.page.custom_company':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The custom company module for getting company related information.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_company_theme() {
  return [
    'custom_company' => [
      'render element' => 'children',
    ],
  ];
}
